spring.application.name=ecommerce-backend

# Cau hinh ket noi SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=JustLifeDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cau hinh Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

payos.client-id=e7683ce3-7310-44a6-be79-155cf0ec7ef1
payos.api-key=7634ac98-2c79-4a39-9fdc-9c45a48dc39a
payos.checksum-key=b9dc3caf3cf56b5be4f806cf38aa439fa8cabe5e86b6081a973f06e21766078f

# URL cua Frontend de PayOS chuyen huong sau khi user tuong tac xong
payos.return-url=http://localhost:3000/payment/success
payos.cancel-url=http://localhost:3000/payment/cancel