spring.application.name=ecommerce-backend

# Cau hinh ket noi PostgreSQL (Local chay cong 5434)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/JustLifeDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cau hinh Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

payos.client-id=${PAYOS_CLIENT_ID:}
payos.api-key=${PAYOS_API_KEY:}
payos.checksum-key=${PAYOS_CHECKSUM_KEY:}

# URL cua Frontend de PayOS chuyen huong sau khi user tuong tac xong
payos.return-url=${PAYOS_RETURN_URL:http://localhost:3000/payment/success}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:3000/payment/cancel}

#Cau hinh Spring Mail Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cau hinh Resend API
resend.api-key=${RESEND_API_KEY:}
resend.from=${RESEND_FROM_EMAIL:onboarding@resend.dev}

# Cau hinh JWT
jwt.secret=${JWT_SECRET:chuoibimatnoidungkhoamaychuAuthenticationJWTDuocKhoiTaoBangMatKhauNay2026}
jwt.expiration=86400000

# Cau hinh Google OAuth2
google.client-id=${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com}
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Jackson Configurations
spring.jackson.deserialization.fail-on-null-for-primitives=false

# Cau hinh Gemini API
gemini.api-key=${GEMINI_API_KEY:}

