spring.application.name=ecommerce-backend

# Cau hinh ket noi SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=JustLifeDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cau hinh Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

payos.client-id=${PAYOS_CLIENT_ID:}
payos.api-key=${PAYOS_API_KEY:}
payos.checksum-key=${PAYOS_CHECKSUM_KEY:}

# URL cua Frontend de PayOS chuyen huong sau khi user tuong tac xong
payos.return-url=http://localhost:3000/payment/success
payos.cancel-url=http://localhost:3000/payment/cancel

#Cau hinh Spring Mail Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cau hinh JWT
jwt.secret=${JWT_SECRET:chuoibimatnoidungkhoamaychuAuthenticationJWTDuocKhoiTaoBangMatKhauNay2026}
jwt.expiration=86400000

# Cau hinh Google OAuth2
google.client-id=${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com}